### ISSUE TITLE
Authentication is failed even with correct api key

### ISSUE THREAD

**Issue by kzhangworks** [ffnarc/T-ARDIS#1]
Hi, appreciated for sharing this tool for learning!  I get an issue and can't figure it out when playing this repo. does anybody have insight for this issue? Thanks for your idea in advance.

I get the following error when executing the command "java -Dumls-apikey="$varname" -jar cpt4.jar 5", and i am sure that the api key is correct and assigned to the variable varname. Looks like the authentication is failed even though the provided api key is right.

```
java -Dumls-apikey="$varname" -jar cpt4.jar 5
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-05-11 20:27:03.638 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  16615/16615
[INFO ] 2022-05-11 21:10:17.932 [main] ConceptService - All cpt4 concepts are processed.
Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://utslogin.nlm.nih.gov//cas/v1/tickets/TGT-56525-30dyni05l31k3o96-cas}
	at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76)
	at org.odhsi.utils.cpt.restclient.RestTicketClient.logout(RestTicketClient.java:113)
	at org.odhsi.utils.cpt.restclient.RestTicketClient.close(RestTicketClient.java:125)
	at org.odhsi.utils.cpt.Application.main(Application.java:49)
```

**Comment by ffnarc** [comment]
Hi,

Thank you for the interest. Try to get the repository from the original source:

https://github.com/cristian931

If the error still persist let us know

**Comment by kzhangworks** [comment]
> Hi, Thank you for the interest. Try to get the repository from the original source: https://github.com/cristian931 If the error still persist let us know
> […](#)
> On Wed, May 11, 2022 at 5:50 PM Kefeng Zhang ***@***.***> wrote: Hi, appreciated for sharing this tool for learning! I get an issue and can't figure it out when playing this repo. does anybody have insight for this issue? Thanks for your idea in advance. I get the following error when executing the command "java -Dumls-apikey="$varname" -jar cpt4.jar 5", and i am sure that the api key is correct and assigned to the variable varname. Looks like the authentication is failed even though the provided api key is right. java -Dumls-apikey="$varname" -jar cpt4.jar 5 WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance. [INFO ] 2022-05-11 20:27:03.638 [main] ConceptService - Writing updated data to CONCEPT.csv Updated CPT4 records: 16615/16615 [INFO ] 2022-05-11 21:10:17.932 [main] ConceptService - All cpt4 concepts are processed. Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://utslogin.nlm.nih.gov//cas/v1/tickets/TGT-56525-30dyni05l31k3o96-cas} at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76) at org.odhsi.utils.cpt.restclient.RestTicketClient.logout(RestTicketClient.java:113) at org.odhsi.utils.cpt.restclient.RestTicketClient.close(RestTicketClient.java:125) at org.odhsi.utils.cpt.Application.main(Application.java:49) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by kzhangworks** [comment]
> Hi, Thank you for the interest. Try to get the repository from the original source: https://github.com/cristian931 If the error still persist let us know
> […](#)
> On Wed, May 11, 2022 at 5:50 PM Kefeng Zhang ***@***.***> wrote: Hi, appreciated for sharing this tool for learning! I get an issue and can't figure it out when playing this repo. does anybody have insight for this issue? Thanks for your idea in advance. I get the following error when executing the command "java -Dumls-apikey="$varname" -jar cpt4.jar 5", and i am sure that the api key is correct and assigned to the variable varname. Looks like the authentication is failed even though the provided api key is right. java -Dumls-apikey="$varname" -jar cpt4.jar 5 WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance. [INFO ] 2022-05-11 20:27:03.638 [main] ConceptService - Writing updated data to CONCEPT.csv Updated CPT4 records: 16615/16615 [INFO ] 2022-05-11 21:10:17.932 [main] ConceptService - All cpt4 concepts are processed. Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://utslogin.nlm.nih.gov//cas/v1/tickets/TGT-56525-30dyni05l31k3o96-cas} at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76) at org.odhsi.utils.cpt.restclient.RestTicketClient.logout(RestTicketClient.java:113) at org.odhsi.utils.cpt.restclient.RestTicketClient.close(RestTicketClient.java:125) at org.odhsi.utils.cpt.Application.main(Application.java:49) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks for your insight, I will look it into including https://github.com/cristian931.
